#!/bin/bash

set -e

perl_versions=(
    5.28.2
    5.30.0
    5.30.1
    5.30.2
    5.30.3
    5.32.1
    5.34.0
    5.34.1
    5.36.0
    5.36.3
    5.38.0
    5.38.2
    5.40.2
)

for perl_version in "${perl_versions[@]}"; do
    mkdir -p "$perl_version"
    cat Dockerfile | sed "s/^ARG PERL_VERSION$/ARG PERL_VERSION=$perl_version/" > "$perl_version/Dockerfile"
done
