#!/bin/bash

set -e

perl_versions=(
    5.36.3
    5.38.2
    5.40.2
    5.42.0
    5.42.3
    5.44.0
)

for perl_version in "${perl_versions[@]}"; do
    mkdir -p "$perl_version"
    cat Dockerfile | sed "s/^ARG PERL_VERSION$/ARG PERL_VERSION=$perl_version/" > "$perl_version/Dockerfile"
done
